# Prediccion de Default en Prestamos

Para este proyecto utilizaremos un sample de los datos de Lending Club. La idea es predecir si cierto usuario cometera Default basado en informacion que la plataforma recolecta. Esto nos ayudara a mejorar la metodologia/pipeline de prestamo.

# Descripcion



Contiene los prestamos de esta plataforma:

    periodo 2007-2017Q3.
    887mil observaciones, sample de 100mil
    150 variables
    Target: loan status

# Objetivo

Realizar un ETL y un EDA

## ETL

0. Limpia los datos de tal manera que al final del ETL queden en formato `tidy`.
1. Asegurate de cargar y leer los datos
2. Crea una tabla donde se guarde el nombre de la columna y el tipo de dato: (`column_name`,   `type`).
3. Asegurate de pensar cual es el tipo de dato correcto. Porque elejiste strig/object o float o int?. No hay respuestas incorrectas como tal, pero tienes que justificar tu decision.
4. Maneja missings o nans de la manera adecuada. Justifica cada decision

## EDA

0. Preparar lo datos para un pipeline de datos
1. Quitar columnas inservibles 
2. Imputar valores
3. Mantener replicabildiad y reproducibilidad

**No olvides anotar tus justificaciones en celdas para recordar cuando te toque explicarlo.** Puedes agregar el numero de celdas que necesites para poner tu explicacion y el codigo, solo manten la estructura.

# ETL

In [260]:
import pandas as pd
import numpy as np

Vas a obtener 2 errores, solucionalo con los visto en clase.  
Tip: Se arreglan con argumentos adicionales de la funcion `read_csv`  
Documentacion: https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

In [261]:
df = pd.read_csv('https://github.com/sonder-art/fdd_prim_2023/blob/main/codigo/pandas/LoansData_sample.csv.gz?raw=true', compression='gzip', encoding='utf-8')
df

/var/folders/d5/0lmbb5vn4dx025fyzx18kp5h0000gn/T/ipykernel_1227/451228320.py:1: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('https://github.com/sonder-art/fdd_prim_2023/blob/main/codigo/pandas/LoansData_sample.csv.gz?raw=true', compression='gzip', encoding='utf-8')

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,0,38098114,NaN,15000.0,15000.0,15000.0,60 months,12.39,336.64,C,C1,MANAGEMENT,10+ years,RENT,78000.0,Source Verified,Dec-2014,Fully Paid,n,NaN,debt_consolidation,Debt consolidation,235xx,VA,12.03,0.0,Aug-1994,750.0,754.0,0.0,NaN,NaN,6.0,0.0,138008.0,29.0,17.0,w,0.00,0.00,17392.370000,17392.37,15000.00,2392.37,0.0,0.00,0.0000,Jun-2016,12017.81,NaN,Nov-2017,684.0,680.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,149140.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184500.0,NaN,NaN,NaN,5.0,29828.0,9525.0,4.7,0.0,0.0,103.0,244.0,1.0,1.0,0.0,47.0,NaN,NaN,NaN,0.0,1.0,4.0,1.0,2.0,8.0,5.0,9.0,4.0,6.0,0.0,0.0,0.0,4.0,100.0,0.0,0.0,0.0,196500.0,149140.0,10000.0,12000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,1,36805548,NaN,10400.0,10400.0,10400.0,36 months,6.99,321.08,A,A3,Truck Driver Delivery Personel,8 years,MORTGAGE,58000.0,Not Verified,Dec-2014,Charged Off,n,NaN,credit_card,Credit card refinancing,937xx,CA,14.92,0.0,Sep-1989,710.0,714.0,2.0,42.0,NaN,17.0,0.0,6133.0,31.6,36.0,w,0.00,0.00,6611.690000,6611.69,5217.75,872.67,0.0,521.27,93.8286,Aug-2016,321.08,NaN,Feb-2017,564.0,560.0,0.0,59.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,162110.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19400.0,NaN,NaN,NaN,7.0,9536.0,7599.0,41.5,0.0,0.0,76.0,290.0,1.0,1.0,1.0,5.0,42.0,1.0,42.0,4.0,6.0,9.0,7.0,18.0,2.0,14.0,32.0,9.0,17.0,0.0,0.0,0.0,4.0,83.3,14.3,0.0,0.0,179407.0,15030.0,13000.0,11325.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,2,37842129,NaN,21425.0,21425.0,21425.0,60 months,15.59,516.36,D,D1,Programming Analysis Supervisor,6 years,RENT,63800.0,Source Verified,Dec-2014,Fully Paid,n,NaN,credit_card,Credit card refinancing,658xx,MO,18.49,0.0,Aug-2003,685.0,689.0,0.0,60.0,NaN,10.0,0.0,16374.0,76.2,35.0,w,0.00,0.00,25512.200000,25512.20,21425.00,4087.20,0.0,0.00,0.0000,May-2016,17813.19,NaN,Dec-2017,704.0,700.0,0.0,74.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,42315.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21500.0,NaN,NaN,NaN,4.0,4232.0,324.0,97.8,0.0,0.0,135.0,136.0,7.0,7.0,0.0,7.0,60.0,7.0,60.0,1.0,3.0,4.0,3.0,12.0,16.0,5.0,18.0,4.0,10.0,0.0,0.0,0.0,2.0,91.4,100.0,0.0,0.0,57073.0,42315.0,15000.0,35573.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,3,37612354,NaN,12800.0,12800.0,12800.0,60 months,17.14,319.08,D,D4,Senior Sales Professional,10+ years,MORTGAGE,125000.0,Verified,Dec-2014,Current,n,NaN,car,Car financing,953xx,CA,8.31,1.0,Oct-2000,665.0,669.0,0.0,17.0,NaN,8.0,0.0,5753.0,100.9,13.0,w,6673.54,6673.54,11207.670000,11207.67,6126.46,5081.21,0.0,0.00,0.0000,Dec-2017,319.08,Jan-2018,Dec-2017,629.0,625.0,0.0,36.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,261815.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5700.0,NaN,NaN,NaN,2.0,32727.0,0.0,103.2,0.0,0.0,16.0,170.0,21.0,16.0,5.0,21.0,17.0,1.0,17.0,1.0,3.0,5.0,3.0,5.0,1.0,5.0,7.0,5.0,8.0,0.0,0.0,0.0,0.0,76.9,100.0,0.0,0.0,368700.0,18007.0,4400.0,18000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,4,37662224,NaN,7650.0,7650.0,7650.0,36 months,13.66,260.20,C,C3,Technical Specialist,< 1 year,RENT,50000.0,Source Verified,Dec-2014,Charged Off,n,NaN,debt_consolidation,Debt consolidation,850xx,AZ,34.81,0.0,Aug-2002,685.0,689.0,1.0,NaN,NaN,11.0,0.0,16822.0,91.9,20.0,f,0.00,0.00,2281.980000,2281.98,704.38,339.61,0.0,1237.99,222.8382,Aug-2015,17.70,NaN,Oct-2016,559.0,555.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,64426.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18300.0,NaN,NaN,NaN,6.0,5857.0,332.0,93.2,0.0,0.0,137.0,148.0,8.0,8.0,0.0,17.0,NaN,3.0,NaN,0.0,1.0,4.0,1.0,4.0,12.0,4.0,8.0,4.0,11.0,0.0,0.0,0.0,2.0,100.0,100.0,0.0,0.0,82331.0,64426.0,4900.0,64031.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99995,22454240,NaN,8400.0,8400.0,8400.0,36 months,9.17,267.79,B,B1,Software Engineer,2 years,MORTGAGE,91000.0,Source Verified,Aug-2014,Fully Paid,n,NaN,debt_consolidation,Debt consolidation,606xx,IL,7.78,1.0,Aug-1990,705.0,709.0,1.0,19.0,54.0,6.0,1.0,8495.0,55.5,16.0,w,0.00,0.00,9640.145407,9640.15,8400.00,1240.15,0.0,0.00,0.0000,Aug-2017,267.50,NaN,Dec-2017,714.0,710.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,152181.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15300.0,NaN,NaN,NaN,2.0,25364.0,2505.0,77.2,0.0,0.0,285.0,287.0,5.0,5.0,1.0,5.0,19.0,5.0,19.0,0.0,2.0,2.0,2.0,6.0,7.0,3.0,7.0,2.0,6.0,0.0,0.0,0.0,2.0,93.7,50.0,0.0,0.0,209557.0,20872.0,11000.0,15473.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
99996,99996,11396920,NaN,10000.0,10000.0,10000.0,36 months,12.99,336.90,C,C1,Assistant Professor of English,3 years,RENT,53133.0,Not Verified,Aug-2014,Fully Paid,n,NaN,debt_consolidation,Debt consolidation,874xx,NM,15.25,0.0,May-2001,690.0,694.0,0.0,NaN,NaN,11.0,0.0,10326.0,42.5,17.0,f,0.00,0.00,11685.080000,11685.08,10000.00,1685.08,0.0,0.00,0.0000,Mar-2016,5594.78,NaN,Dec-2017,684.0,680.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,98.0,46413.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24300.0,NaN,NaN,NaN,3.0,4219.0,13974.0,42.5,0.0,0.0,77.0,158.0,5.0,5.0,0.0,5.0,NaN,24.0,NaN,0.0,5.0,5.0,9.0,11.0,4.0,9.0,13.0,5.0,11.0,0.0,0.0,0.0,1.0,100.0,11.1,0.0,0.0,64149.0,46413.0,24300.0,39849.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
99997,99997,8556176,NaN,30000.0,30000.0,30000.0,60 months,20.99,811.44,E,E4,Facilities Tech 3,10+ years,RENT,78000.0,Verified,Aug-2014,Current,n,NaN,debt_consolidation,Debt consolidation,926xx,CA,23.75,0.0,Jun-1998,665.0,669.0,1.0,29.0,NaN,18.0,0.0,27409.0,79.0,30.0,w,13599.63,13599.63,32530.430000,32530.43,16400.37,16130.06,0.0,0.00,0.0000,Dec-2017,811.44,Jan-2018,Dec-2017,624.0,620.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,345934.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34700.0,NaN,NaN,NaN,5.0,20349.0,2354.0,89.4,0.0,0.0,155.0,193.0,1.0,1.0,2.0,12.0,29.0,1.0,29.0,0.0,7.0,12.0,7.0,9.0,5.0,15.0,22.0,12.0,18.0,0.0,0.0,0.0,4.0,93.3,100.0,0.0,0.0,371088.0,45447.0,22300.0,25212.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
99998,99998,24023408,NaN,8475.0,8475.0,8475.0,36 months,24.99,336.92,F,F4,Records Examiner Analyst,10+ years,RENT,52000.0,Verified,Aug-2014,Charged Off,n,NaN,debt_consolidation,Debt consolidation,630xx,MO,17.61,2.0,Nov-2000,660.0,664.0,1.0,13.0,83.0,11.0,1.0,2962.0,35.7,29.0,f,0.00,0.00,2695.360000,2695.36,1380.97,1314.39,0.0,0.00,0.0000,Apr-2015,336.92,NaN,Dec-2017,609.0,605.0,0.0,17.0,1.0,Individual,NaN,NaN,NaN,0.0,2066.0,31247.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8300.0,NaN,NaN,NaN,8.0,3125.0,324.0,88.0,0.0,0.0,141.0,164.0,7.0,1.0,0.0,7.0,17.0,4.0,17.0,2.0,1.0,3.0,1.0,4.0,11.0,8.0,18.0,3.0,11.0,0.0,0.0,1.0,6.0,86.4,100.0,1.0,0.0,43686.0,31247.0,2700.0,35386.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
99999,99999,24023398,NaN,25000.0,25000.0,25000.0,36 months,10.15,808.45,B,B2,Occupational Theapy Assistant,3 years,OWN,60000.0,Source Verified,Aug-2014,Fully Paid,n,NaN,debt_consolidation,Debt consolidation,468xx,IN,27.82,0.0,Jul-1999,730.0,734.0,0.0,NaN,NaN,23.0,0.0,23719.0,40.3,35.0,w,0.00,0.00,29024.061162,29024.06,25000.00,4024.06,0.0,0.00,0.0000,Mar-2017,4759.78,NaN,Dec-2017,754.0,750.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,233053.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58900.0,NaN,NaN,NaN,5.0,10133.0,17153.0,57.4,0.0,0.0,104.0,180.0,1.0,1.0,2.0,8.0,NaN,13.0,NaN,0.0,5.0,7.0,5.0,9.0,13.0,10.0,19.0,7.0,23.0,0.0,0.0,0.0,3.0,100.0,40.0,0.0,0.0,290888.0,71301.0,40300.0,64888.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

# limpia rapida

Al cargar los datos hay ciertos errores, donde se recorrieron dos columnas a simple vista, asi que lo que hacemos es que la info de la columna member_id se paso a la columna Unamed:0 y la info de la columna Unamed:0 tiene los id's asi que arreglamos eso, deshaciendonos de Unmaed:0 y pasandole la informacion correcta a id y a member_id

In [262]:


try:
    df['member_id'] = df['id']
    df.drop(columns=['id'], inplace=True)
except KeyError:
    print("Error: 'id' column not found.")

# Checa si existe la columna 'Unnamed: 0' y la renombra a 'id'
if 'Unnamed: 0' in df.columns:
    df.rename(columns={'Unnamed: 0': 'id'}, inplace=True)

# Checa si existe la columna 'id' y la convierte en índice
try:
    df.set_index('id', inplace=True)
except KeyError:
    print("Error: 'id' column not found.")

df

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,38098114,15000.0,15000.0,15000.0,60 months,12.39,336.64,C,C1,MANAGEMENT,10+ years,RENT,78000.0,Source Verified,Dec-2014,Fully Paid,n,NaN,debt_consolidation,Debt consolidation,235xx,VA,12.03,0.0,Aug-1994,750.0,754.0,0.0,NaN,NaN,6.0,0.0,138008.0,29.0,17.0,w,0.00,0.00,17392.370000,17392.37,15000.00,2392.37,0.0,0.00,0.0000,Jun-2016,12017.81,NaN,Nov-2017,684.0,680.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,149140.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184500.0,NaN,NaN,NaN,5.0,29828.0,9525.0,4.7,0.0,0.0,103.0,244.0,1.0,1.0,0.0,47.0,NaN,NaN,NaN,0.0,1.0,4.0,1.0,2.0,8.0,5.0,9.0,4.0,6.0,0.0,0.0,0.0,4.0,100.0,0.0,0.0,0.0,196500.0,149140.0,10000.0,12000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,36805548,10400.0,10400.0,10400.0,36 months,6.99,321.08,A,A3,Truck Driver Delivery Personel,8 years,MORTGAGE,58000.0,Not Verified,Dec-2014,Charged Off,n,NaN,credit_card,Credit card refinancing,937xx,CA,14.92,0.0,Sep-1989,710.0,714.0,2.0,42.0,NaN,17.0,0.0,6133.0,31.6,36.0,w,0.00,0.00,6611.690000,6611.69,5217.75,872.67,0.0,521.27,93.8286,Aug-2016,321.08,NaN,Feb-2017,564.0,560.0,0.0,59.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,162110.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19400.0,NaN,NaN,NaN,7.0,9536.0,7599.0,41.5,0.0,0.0,76.0,290.0,1.0,1.0,1.0,5.0,42.0,1.0,42.0,4.0,6.0,9.0,7.0,18.0,2.0,14.0,32.0,9.0,17.0,0.0,0.0,0.0,4.0,83.3,14.3,0.0,0.0,179407.0,15030.0,13000.0,11325.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,37842129,21425.0,21425.0,21425.0,60 months,15.59,516.36,D,D1,Programming Analysis Supervisor,6 years,RENT,63800.0,Source Verified,Dec-2014,Fully Paid,n,NaN,credit_card,Credit card refinancing,658xx,MO,18.49,0.0,Aug-2003,685.0,689.0,0.0,60.0,NaN,10.0,0.0,16374.0,76.2,35.0,w,0.00,0.00,25512.200000,25512.20,21425.00,4087.20,0.0,0.00,0.0000,May-2016,17813.19,NaN,Dec-2017,704.0,700.0,0.0,74.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,42315.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21500.0,NaN,NaN,NaN,4.0,4232.0,324.0,97.8,0.0,0.0,135.0,136.0,7.0,7.0,0.0,7.0,60.0,7.0,60.0,1.0,3.0,4.0,3.0,12.0,16.0,5.0,18.0,4.0,10.0,0.0,0.0,0.0,2.0,91.4,100.0,0.0,0.0,57073.0,42315.0,15000.0,35573.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,37612354,12800.0,12800.0,12800.0,60 months,17.14,319.08,D,D4,Senior Sales Professional,10+ years,MORTGAGE,125000.0,Verified,Dec-2014,Current,n,NaN,car,Car financing,953xx,CA,8.31,1.0,Oct-2000,665.0,669.0,0.0,17.0,NaN,8.0,0.0,5753.0,100.9,13.0,w,6673.54,6673.54,11207.670000,11207.67,6126.46,5081.21,0.0,0.00,0.0000,Dec-2017,319.08,Jan-2018,Dec-2017,629.0,625.0,0.0,36.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,261815.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5700.0,NaN,NaN,NaN,2.0,32727.0,0.0,103.2,0.0,0.0,16.0,170.0,21.0,16.0,5.0,21.0,17.0,1.0,17.0,1.0,3.0,5.0,3.0,5.0,1.0,5.0,7.0,5.0,8.0,0.0,0.0,0.0,0.0,76.9,100.0,0.0,0.0,368700.0,18007.0,4400.0,18000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,37662224,7650.0,7650.0,7650.0,36 months,13.66,260.20,C,C3,Technical Specialist,< 1 year,RENT,50000.0,Source Verified,Dec-2014,Charged Off,n,NaN,debt_consolidation,Debt consolidation,850xx,AZ,34.81,0.0,Aug-2002,685.0,689.0,1.0,NaN,NaN,11.0,0.0,16822.0,91.9,20.0,f,0.00,0.00,2281.980000,2281.98,704.38,339.61,0.0,1237.99,222.8382,Aug-2015,17.70,NaN,Oct-2016,559.0,555.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,64426.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18300.0,NaN,NaN,NaN,6.0,5857.0,332.0,93.2,0.0,0.0,137.0,148.0,8.0,8.0,0.0,17.0,NaN,3.0,NaN,0.0,1.0,4.0,1.0,4.0,12.0,4.0,8.0,4.0,11.0,0.0,0.0,0.0,2.0,100.0,100.0,0.0,0.0,82331.0,64426.0,4900.0,64031.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,22454240,8400.0,8400.0,8400.0,36 months,9.17,267.79,B,B1,Software Engineer,2 years,MORTGAGE,91000.0,Source Verified,Aug-2014,Fully Paid,n,NaN,debt_consolidation,Debt consolidation,606xx,IL,7.78,1.0,Aug-1990,705.0,709.0,1.0,19.0,54.0,6.0,1.0,8495.0,55.5,16.0,w,0.00,0.00,9640.145407,9640.15,8400.00,1240.15,0.0,0.00,0.0000,Aug-2017,267.50,NaN,Dec-2017,714.0,710.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,152181.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15300.0,NaN,NaN,NaN,2.0,25364.0,2505.0,77.2,0.0,0.0,285.0,287.0,5.0,5.0,1.0,5.0,19.0,5.0,19.0,0.0,2.0,2.0,2.0,6.0,7.0,3.0,7.0,2.0,6.0,0.0,0.0,0.0,2.0,93.7,50.0,0.0,0.0,209557.0,20872.0,11000.0,15473.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
99996,11396920,10000.0,10000.0,10000.0,36 months,12.99,336.90,C,C1,Assistant Professor of English,3 years,RENT,53133.0,Not Verified,Aug-2014,Fully Paid,n,NaN,debt_consolidation,Debt consolidation,874xx,NM,15.25,0.0,May-2001,690.0,694.0,0.0,NaN,NaN,11.0,0.0,10326.0,42.5,17.0,f,0.00,0.00,11685.080000,11685.08,10000.00,1685.08,0.0,0.00,0.0000,Mar-2016,5594.78,NaN,Dec-2017,684.0,680.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,98.0,46413.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24300.0,NaN,NaN,NaN,3.0,4219.0,13974.0,42.5,0.0,0.0,77.0,158.0,5.0,5.0,0.0,5.0,NaN,24.0,NaN,0.0,5.0,5.0,9.0,11.0,4.0,9.0,13.0,5.0,11.0,0.0,0.0,0.0,1.0,100.0,11.1,0.0,0.0,64149.0,46413.0,24300.0,39849.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
99997,8556176,30000.0,30000.0,30000.0,60 months,20.99,811.44,E,E4,Facilities Tech 3,10+ years,RENT,78000.0,Verified,Aug-2014,Current,n,NaN,debt_consolidation,Debt consolidation,926xx,CA,23.75,0.0,Jun-1998,665.0,669.0,1.0,29.0,NaN,18.0,0.0,27409.0,79.0,30.0,w,13599.63,13599.63,32530.430000,32530.43,16400.37,16130.06,0.0,0.00,0.0000,Dec-2017,811.44,Jan-2018,Dec-2017,624.0,620.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,345934.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34700.0,NaN,NaN,NaN,5.0,20349.0,2354.0,89.4,0.0,0.0,155.0,193.0,1.0,1.0,2.0,12.0,29.0,1.0,29.0,0.0,7.0,12.0,7.0,9.0,5.0,15.0,22.0,12.0,18.0,0.0,0.0,0.0,4.0,93.3,100.0,0.0,0.0,371088.0,45447.0,22300.0,25212.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
99998,24023408,8475.0,8475.0,8475.0,36 months,24.99,336.92,F,F4,Records Examiner Analyst,10+ years,RENT,52000.0,Verified,Aug-2014,Charged Off,n,NaN,debt_consolidation,Debt consolidation,630xx,MO,17.61,2.0,Nov-2000,660.0,664.0,1.0,13.0,83.0,11.0,1.0,2962.0,35.7,29.0,f,0.00,0.00,2695.360000,2695.36,1380.97,1314.39,0.0,0.00,0.0000,Apr-2015,336.92,NaN,Dec-2017,609.0,605.0,0.0,17.0,1.0,Individual,NaN,NaN,NaN,0.0,2066.0,31247.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8300.0,NaN,NaN,NaN,8.0,3125.0,324.0,88.0,0.0,0.0,141.0,164.0,7.0,1.0,0.0,7.0,17.0,4.0,17.0,2.0,1.0,3.0,1.0,4.0,11.0,8.0,18.0,3.0,11.0,0.0,0.0,1.0,6.0,86.4,100.0,1.0,0.0,43686.0,31247.0,2700.0,35386.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
99999,24023398,25000.0,25000.0,25000.0,36 months,10.15,808.45,B,B2,Occupational Theapy Assistant,3 years,OWN,60000.0,Source Verified,Aug-2014,Fully Paid,n,NaN,debt_consolidation,Debt consolidation,468xx,IN,27.82,0.0,Jul-1999,730.0,734.0,0.0,NaN,NaN,23.0,0.0,23719.0,40.3,35.0,w,0.00,0.00,29024.061162,29024.06,25000.00,4024.06,0.0,0.00,0.0000,Mar-2017,4759.78,NaN,Dec-2017,754.0,750.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,233053.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58900.0,NaN,NaN,NaN,5.0,10133.0,17153.0,57.4,0.0,0.0,104.0,180.0,1.0,1.0,2.0,8.0,NaN,13.0,NaN,0.0,5.0,7.0,5.0,9.0,13.0,10.0,19.0,7.0,23.0,0.0,0.0,0.0,3.0,100.0,40.0,0.0,0.0,290888.0,71301.0,40300.0,64888.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

## Tabla (column_name, type)

Revisa el metodo pd.DataFrame.dtypes. https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dtypes.html

In [263]:
column_types = df.dtypes

In [264]:
#hacemos algunos cambios para que se vea mejor

column_types = df.dtypes
features = pd.DataFrame(column_types ,columns=['type']).reset_index()
features.rename(columns={'index':'feature'}, inplace=True)


features

                   feature     type
0                member_id    int64
1                loan_amnt  float64
2              funded_amnt  float64
3          funded_amnt_inv  float64
4                     term   object
..                     ...      ...
144      settlement_status   object
145        settlement_date   object
146      settlement_amount  float64
147  settlement_percentage  float64
148        settlement_term  float64

[149 rows x 2 columns]

## Cargar descripcion de columnas

La siguiente tabla tiene una descripcion del significado de cada columna

In [265]:


datos_dict = pd.read_excel(
    'https://resources.lendingclub.com/LCDataDictionary.xlsx')
datos_dict.columns = ['feature', 'description']
datos_dict

                   feature                                        description
0           acc_now_delinq  The number of accounts on which the borrower i...
1     acc_open_past_24mths         Number of trades opened in past 24 months.
2               addr_state  The state provided by the borrower in the loan...
3                 all_util              Balance to credit limit on all trades
4               annual_inc  The self-reported annual income provided by th...
..                     ...                                                ...
148      settlement_amount  The loan amount that the borrower has agreed t...
149  settlement_percentage  The settlement amount as a percentage of the p...
150        settlement_term  The number of months that the borrower will be...
151                    NaN                                                NaN
152                    NaN  * Employer Title replaces Employer Name for al...

[153 rows x 2 columns]

In [266]:

#nos deshacemos de todos los nans, ya que hay ciertas ambiguedades
datos_dict.dropna(inplace=True)
datos_dict

                   feature                                        description
0           acc_now_delinq  The number of accounts on which the borrower i...
1     acc_open_past_24mths         Number of trades opened in past 24 months.
2               addr_state  The state provided by the borrower in the loan...
3                 all_util              Balance to credit limit on all trades
4               annual_inc  The self-reported annual income provided by th...
..                     ...                                                ...
146      settlement_status  The status of the borrower’s settlement plan. ...
147        settlement_date  The date that the borrower agrees to the settl...
148      settlement_amount  The loan amount that the borrower has agreed t...
149  settlement_percentage  The settlement amount as a percentage of the p...
150        settlement_term  The number of months that the borrower will be...

[151 rows x 2 columns]

### Pickle

Crea codigo para **guardar** y **cargar** el DataFrame de `datos_dict` creada en las celdas anteriores en formato **pickle**

In [267]:
# COdigo guardar
#guardamos datos_dict en un pickle
datos_dict.to_pickle('columnas.pkl')

In [268]:
# leemos el pickle
df_desc = pd.read_pickle('columnas.pkl')
df_desc

                   feature                                        description
0           acc_now_delinq  The number of accounts on which the borrower i...
1     acc_open_past_24mths         Number of trades opened in past 24 months.
2               addr_state  The state provided by the borrower in the loan...
3                 all_util              Balance to credit limit on all trades
4               annual_inc  The self-reported annual income provided by th...
..                     ...                                                ...
146      settlement_status  The status of the borrower’s settlement plan. ...
147        settlement_date  The date that the borrower agrees to the settl...
148      settlement_amount  The loan amount that the borrower has agreed t...
149  settlement_percentage  The settlement amount as a percentage of the p...
150        settlement_term  The number of months that the borrower will be...

[151 rows x 2 columns]

## Tipos de Datos

Realiza las transformaciones o casteos (casting) que creas necesarios a tus datos de tal manera que el typo de dato sea adecuado. Al terminar recrea la tabla `column_types` con los nuevos tipos.

No olvides anotar tus justificaciones para recordar cuando te toque explicarlo.

# Proceso
Primero hacemos un enfoque en la tabla features en la que podemos ver que cambios hay que hacerles a ciertos types especificos dependiendo de su definicion, a todos los dates es importante ponerlos en formato de date, encontraamos todos los features que tengan date y decimos que su tipo seaa datetime64.
Ahora el resto de las columnas fijemonos en 2, type float64 y type int64, los id los dejamos en int64, ya que ssiempre seran numeros enteross y salvan memoria, y los amounts seran float64.
Ahora los objects todos los dejaremos en el mismo formato, porque puede ser que haya cierto momento en donde tengamos que usar regex, para buscar cierto requerimiento, pero siempre puedes convertir el type object en string estrictamente, asi que no es problema.
Lo que haremos ahorita, es cambiar todos los dates, a datetime64 y todos las columnas con int64 y float64 a sus types correspondientes, lo demas lo dejaremos de la misma manera.

primero en la tabla features cambiamos todos los dates al type datetime64 en vez de dejarlos en objects

In [269]:
import re 
import datetime
# Manejos de tipos 1

rexp = '(date)'
index = []
def dateinstance(exp):
    date = str(exp)
    result = re.findall(rexp,date)
    if result:
        filt = (features['feature']==exp)
        features.loc[filt,'type'] = 'datetime64'
        

features['feature'].apply(dateinstance)
pd.set_option('display.max_rows', None)
print(features)
pd.reset_option('display.max_rows')
#checamos cuantos int64 hay
filt = (features['type']=='int64')
features.loc[filt]

                                        feature        type
0                                     member_id       int64
1                                     loan_amnt     float64
2                                   funded_amnt     float64
3                               funded_amnt_inv     float64
4                                          term      object
5                                      int_rate     float64
6                                   installment     float64
7                                         grade      object
8                                     sub_grade      object
9                                     emp_title      object
10                                   emp_length      object
11                               home_ownership      object
12                                   annual_inc     float64
13                          verification_status      object
14                                      issue_d      object
15                                  loan_status      object
16                                   pymnt_plan      object
17                                         desc      object
18                                      purpose      object
19                                        title      object
20                                     zip_code      object
21                                   addr_state      object
22                                          dti     float64
23                                  delinq_2yrs     float64
24                             earliest_cr_line      object
25                               fico_range_low     float64
26                              fico_range_high     float64
27                               inq_last_6mths     float64
28                       mths_since_last_delinq     float64
29                       mths_since_last_record     float64
30                                     open_acc     float64
31                                      pub_rec     float64
32                                    revol_bal     float64
33                                   revol_util     float64
34                                    total_acc     float64
35                          initial_list_status      object
36                                    out_prncp     float64
37                                out_prncp_inv     float64
38                                  total_pymnt     float64
39                              total_pymnt_inv     float64
40                              total_rec_prncp     float64
41                                total_rec_int     float64
42                           total_rec_late_fee     float64
43                                   recoveries     float64
44                      collection_recovery_fee     float64
45                                 last_pymnt_d      object
46                              last_pymnt_amnt     float64
47                                 next_pymnt_d      object
48                           last_credit_pull_d      object
49                         last_fico_range_high     float64
50                          last_fico_range_low     float64
51                   collections_12_mths_ex_med     float64
52                  mths_since_last_major_derog     float64
53                                  policy_code     float64
54                             application_type      object
55                             annual_inc_joint     float64
56                                    dti_joint     float64
57                    verification_status_joint     float64
58                               acc_now_delinq     float64
59                                 tot_coll_amt     float64
60                                  tot_cur_bal     float64
61                                  open_acc_6m     float64
62                                  open_act_il     float64
63                                  open_il_12m     float64
64                                  open_il_24m     float64
65                           mths_since_rcnt_il     float64
66                                 total_bal_il     float64
67                                      il_util     float64
68                                  open_rv_12m     float64
69                                  open_rv_24m     float64
70                                   max_bal_bc     float64
71                                     all_util     float64
72                             total_rev_hi_lim     float64
73                                       inq_fi     float64
74                                  total_cu_tl     float64
75                                 inq_last_12m     float64
76                         acc_open_past_24mths     float64
77                                  avg_cur_bal     float64
78                               bc_open_to_buy     float64
79                                      bc_util     float64
80                     chargeoff_within_12_mths     float64
81                                  delinq_amnt     float64
82                           mo_sin_old_il_acct     float64
83                         mo_sin_old_rev_tl_op     float64
84                        mo_sin_rcnt_rev_tl_op     float64
85                               mo_sin_rcnt_tl     float64
86                                     mort_acc     float64
87                         mths_since_recent_bc     float64
88                     mths_since_recent_bc_dlq     float64
89                        mths_since_recent_inq     float64
90               mths_since_recent_revol_delinq     float64
91                        num_accts_ever_120_pd     float64
92                               num_actv_bc_tl     float64
93                              num_actv_rev_tl     float64
94                                  num_bc_sats     float64
95                                    num_bc_tl     float64
96                                    num_il_tl     float64
97                                num_op_rev_tl     float64
98                                num_rev_accts     float64
99                          num_rev_tl_bal_gt_0     float64
100                                    num_sats     float64
101                            num_tl_120dpd_2m     float64
102                                num_tl_30dpd     float64
103                          num_tl_90g_dpd_24m     float64
104                          num_tl_op_past_12m     float64
105                              pct_tl_nvr_dlq     float64
106                            percent_bc_gt_75     float64
107                        pub_rec_bankruptcies     float64
108                                   tax_liens     float64
109                             tot_hi_cred_lim     float64
110                           total_bal_ex_mort     float64
111                              total_bc_limit     float64
112                  total_il_high_credit_limit     float64
113                             revol_bal_joint     float64
114                      sec_app_fico_range_low     float64
115                     sec_app_fico_range_high     float64
116                    sec_app_earliest_cr_line     float64
117                      sec_app_inq_last_6mths     float64
118                            sec_app_mort_acc     float64
119                            sec_app_open_acc     float64
120                          sec_app_revol_util     float64
121                         sec_app_open_act_il     float64
122                       sec_app_num_rev_accts     float64
123            sec_app_chargeoff_within_12_mths     float64
124          sec_app_collections_12_mths_ex_med     float64
125         sec_app_mths_since_last_major_derog     float64
126                               hardship_flag      object
127                               hardship_type      object
128                             hardship_reason      object
129                             hardship_status      object
130                               deferral_term     float64
131                             hardship_amount     float64
132                         hardship_start_date  datetime64
133                           hardship_end_date  datetime64
134                     payment_plan_start_date  datetime64
135                             hardship_length     float64
136                                hardship_dpd     float64
137                        hardship_loan_status      object
138  orig_projected_additional_accrued_interest     float64
139              hardship_payoff_balance_amount     float64
140                hardship_last_payment_amount     float64
141                         disbursement_method      object
142                        debt_settlement_flag      object
143                   debt_settlement_flag_date  datetime64
144                           settlement_status      object
145                             settlement_date  datetime64
146                           settlement_amount     float64
147                       settlement_percentage     float64
148                             settlement_term     float64

     feature   type
0  member_id  int64

Ahora iteramos sobre features para castear en el dataframe la columna segun el type

In [270]:
#iteramos sobre las rows de features
for index,row in features.iterrows():
    #si es datetime64 lo cambiamos a ese tipo de dato porque es un date
    if row['type'] == 'datetime64':
        try:
            df[row['feature']] = pd.to_datetime(df[row['feature']],format='%Y-%m-%d')
        except:
            pass
    else:
    #en este cas dependiendo del tipo de dato cambiamos la columna a ese tipo
        try:
            df[row['feature']] = df[row['feature']].astype(row['type'])
        except:
            pass
df

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,38098114,15000.0,15000.0,15000.0,60 months,12.39,336.64,C,C1,MANAGEMENT,10+ years,RENT,78000.0,Source Verified,Dec-2014,Fully Paid,n,NaN,debt_consolidation,Debt consolidation,235xx,VA,12.03,0.0,Aug-1994,750.0,754.0,0.0,NaN,NaN,6.0,0.0,138008.0,29.0,17.0,w,0.00,0.00,17392.370000,17392.37,15000.00,2392.37,0.0,0.00,0.0000,Jun-2016,12017.81,NaN,Nov-2017,684.0,680.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,149140.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184500.0,NaN,NaN,NaN,5.0,29828.0,9525.0,4.7,0.0,0.0,103.0,244.0,1.0,1.0,0.0,47.0,NaN,NaN,NaN,0.0,1.0,4.0,1.0,2.0,8.0,5.0,9.0,4.0,6.0,0.0,0.0,0.0,4.0,100.0,0.0,0.0,0.0,196500.0,149140.0,10000.0,12000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,36805548,10400.0,10400.0,10400.0,36 months,6.99,321.08,A,A3,Truck Driver Delivery Personel,8 years,MORTGAGE,58000.0,Not Verified,Dec-2014,Charged Off,n,NaN,credit_card,Credit card refinancing,937xx,CA,14.92,0.0,Sep-1989,710.0,714.0,2.0,42.0,NaN,17.0,0.0,6133.0,31.6,36.0,w,0.00,0.00,6611.690000,6611.69,5217.75,872.67,0.0,521.27,93.8286,Aug-2016,321.08,NaN,Feb-2017,564.0,560.0,0.0,59.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,162110.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19400.0,NaN,NaN,NaN,7.0,9536.0,7599.0,41.5,0.0,0.0,76.0,290.0,1.0,1.0,1.0,5.0,42.0,1.0,42.0,4.0,6.0,9.0,7.0,18.0,2.0,14.0,32.0,9.0,17.0,0.0,0.0,0.0,4.0,83.3,14.3,0.0,0.0,179407.0,15030.0,13000.0,11325.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,37842129,21425.0,21425.0,21425.0,60 months,15.59,516.36,D,D1,Programming Analysis Supervisor,6 years,RENT,63800.0,Source Verified,Dec-2014,Fully Paid,n,NaN,credit_card,Credit card refinancing,658xx,MO,18.49,0.0,Aug-2003,685.0,689.0,0.0,60.0,NaN,10.0,0.0,16374.0,76.2,35.0,w,0.00,0.00,25512.200000,25512.20,21425.00,4087.20,0.0,0.00,0.0000,May-2016,17813.19,NaN,Dec-2017,704.0,700.0,0.0,74.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,42315.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21500.0,NaN,NaN,NaN,4.0,4232.0,324.0,97.8,0.0,0.0,135.0,136.0,7.0,7.0,0.0,7.0,60.0,7.0,60.0,1.0,3.0,4.0,3.0,12.0,16.0,5.0,18.0,4.0,10.0,0.0,0.0,0.0,2.0,91.4,100.0,0.0,0.0,57073.0,42315.0,15000.0,35573.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,37612354,12800.0,12800.0,12800.0,60 months,17.14,319.08,D,D4,Senior Sales Professional,10+ years,MORTGAGE,125000.0,Verified,Dec-2014,Current,n,NaN,car,Car financing,953xx,CA,8.31,1.0,Oct-2000,665.0,669.0,0.0,17.0,NaN,8.0,0.0,5753.0,100.9,13.0,w,6673.54,6673.54,11207.670000,11207.67,6126.46,5081.21,0.0,0.00,0.0000,Dec-2017,319.08,Jan-2018,Dec-2017,629.0,625.0,0.0,36.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,261815.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5700.0,NaN,NaN,NaN,2.0,32727.0,0.0,103.2,0.0,0.0,16.0,170.0,21.0,16.0,5.0,21.0,17.0,1.0,17.0,1.0,3.0,5.0,3.0,5.0,1.0,5.0,7.0,5.0,8.0,0.0,0.0,0.0,0.0,76.9,100.0,0.0,0.0,368700.0,18007.0,4400.0,18000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,37662224,7650.0,7650.0,7650.0,36 months,13.66,260.20,C,C3,Technical Specialist,< 1 year,RENT,50000.0,Source Verified,Dec-2014,Charged Off,n,NaN,debt_consolidation,Debt consolidation,850xx,AZ,34.81,0.0,Aug-2002,685.0,689.0,1.0,NaN,NaN,11.0,0.0,16822.0,91.9,20.0,f,0.00,0.00,2281.980000,2281.98,704.38,339.61,0.0,1237.99,222.8382,Aug-2015,17.70,NaN,Oct-2016,559.0,555.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,64426.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18300.0,NaN,NaN,NaN,6.0,5857.0,332.0,93.2,0.0,0.0,137.0,148.0,8.0,8.0,0.0,17.0,NaN,3.0,NaN,0.0,1.0,4.0,1.0,4.0,12.0,4.0,8.0,4.0,11.0,0.0,0.0,0.0,2.0,100.0,100.0,0.0,0.0,82331.0,64426.0,4900.0,64031.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,22454240,8400.0,8400.0,8400.0,36 months,9.17,267.79,B,B1,Software Engineer,2 years,MORTGAGE,91000.0,Source Verified,Aug-2014,Fully Paid,n,NaN,debt_consolidation,Debt consolidation,606xx,IL,7.78,1.0,Aug-1990,705.0,709.0,1.0,19.0,54.0,6.0,1.0,8495.0,55.5,16.0,w,0.00,0.00,9640.145407,9640.15,8400.00,1240.15,0.0,0.00,0.0000,Aug-2017,267.50,NaN,Dec-2017,714.0,710.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,152181.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15300.0,NaN,NaN,NaN,2.0,25364.0,2505.0,77.2,0.0,0.0,285.0,287.0,5.0,5.0,1.0,5.0,19.0,5.0,19.0,0.0,2.0,2.0,2.0,6.0,7.0,3.0,7.0,2.0,6.0,0.0,0.0,0.0,2.0,93.7,50.0,0.0,0.0,209557.0,20872.0,11000.0,15473.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
99996,11396920,10000.0,10000.0,10000.0,36 months,12.99,336.90,C,C1,Assistant Professor of English,3 years,RENT,53133.0,Not Verified,Aug-2014,Fully Paid,n,NaN,debt_consolidation,Debt consolidation,874xx,NM,15.25,0.0,May-2001,690.0,694.0,0.0,NaN,NaN,11.0,0.0,10326.0,42.5,17.0,f,0.00,0.00,11685.080000,11685.08,10000.00,1685.08,0.0,0.00,0.0000,Mar-2016,5594.78,NaN,Dec-2017,684.0,680.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,98.0,46413.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24300.0,NaN,NaN,NaN,3.0,4219.0,13974.0,42.5,0.0,0.0,77.0,158.0,5.0,5.0,0.0,5.0,NaN,24.0,NaN,0.0,5.0,5.0,9.0,11.0,4.0,9.0,13.0,5.0,11.0,0.0,0.0,0.0,1.0,100.0,11.1,0.0,0.0,64149.0,46413.0,24300.0,39849.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
99997,8556176,30000.0,30000.0,30000.0,60 months,20.99,811.44,E,E4,Facilities Tech 3,10+ years,RENT,78000.0,Verified,Aug-2014,Current,n,NaN,debt_consolidation,Debt consolidation,926xx,CA,23.75,0.0,Jun-1998,665.0,669.0,1.0,29.0,NaN,18.0,0.0,27409.0,79.0,30.0,w,13599.63,13599.63,32530.430000,32530.43,16400.37,16130.06,0.0,0.00,0.0000,Dec-2017,811.44,Jan-2018,Dec-2017,624.0,620.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,345934.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34700.0,NaN,NaN,NaN,5.0,20349.0,2354.0,89.4,0.0,0.0,155.0,193.0,1.0,1.0,2.0,12.0,29.0,1.0,29.0,0.0,7.0,12.0,7.0,9.0,5.0,15.0,22.0,12.0,18.0,0.0,0.0,0.0,4.0,93.3,100.0,0.0,0.0,371088.0,45447.0,22300.0,25212.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
99998,24023408,8475.0,8475.0,8475.0,36 months,24.99,336.92,F,F4,Records Examiner Analyst,10+ years,RENT,52000.0,Verified,Aug-2014,Charged Off,n,NaN,debt_consolidation,Debt consolidation,630xx,MO,17.61,2.0,Nov-2000,660.0,664.0,1.0,13.0,83.0,11.0,1.0,2962.0,35.7,29.0,f,0.00,0.00,2695.360000,2695.36,1380.97,1314.39,0.0,0.00,0.0000,Apr-2015,336.92,NaN,Dec-2017,609.0,605.0,0.0,17.0,1.0,Individual,NaN,NaN,NaN,0.0,2066.0,31247.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8300.0,NaN,NaN,NaN,8.0,3125.0,324.0,88.0,0.0,0.0,141.0,164.0,7.0,1.0,0.0,7.0,17.0,4.0,17.0,2.0,1.0,3.0,1.0,4.0,11.0,8.0,18.0,3.0,11.0,0.0,0.0,1.0,6.0,86.4,100.0,1.0,0.0,43686.0,31247.0,2700.0,35386.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
99999,24023398,25000.0,25000.0,25000.0,36 months,10.15,808.45,B,B2,Occupational Theapy Assistant,3 years,OWN,60000.0,Source Verified,Aug-2014,Fully Paid,n,NaN,debt_consolidation,Debt consolidation,468xx,IN,27.82,0.0,Jul-1999,730.0,734.0,0.0,NaN,NaN,23.0,0.0,23719.0,40.3,35.0,w,0.00,0.00,29024.061162,29024.06,25000.00,4024.06,0.0,0.00,0.0000,Mar-2017,4759.78,NaN,Dec-2017,754.0,750.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,233053.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58900.0,NaN,NaN,NaN,5.0,10133.0,17153.0,57.4,0.0,0.0,104.0,180.0,1.0,1.0,2.0,8.0,NaN,13.0,NaN,0.0,5.0,7.0,5.0,9.0,13.0,10.0,19.0,7.0,23.0,0.0,0.0,0.0,3.0,100.0,40.0,0.0,0.0,290888.0,71301.0,40300.0,64888.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

## Manejo de NaNs o missings

Maneja los datos de tipos missing. Elije una estrategia adecuada dependiendo del tipo de dato que le asignaste a la columna.

Crea codigo para **guardar** y **cargar** un archivo JSON en el que se guarde la `estrategia` y `valor` que utilizaste para **imputar**. Por ejemplo: Si hay una columna que se llama `columna 3` y utilizaste la estrategia de imputacion de media, y existe otra llamada `columna 4` y  elegiste la palabra 'missing' el JSON debera contener:  
  
 `{'columna 3':{'estrategia':'mean', 'valor':3.4}, 'columna 4':{'estrategia':'identificador', 'valor':'missing'}}`  

 De tal manera que para cada columna que tenga un metodo de imputacion apunte a otro diccionario donde el **key** `estrategia` describa de manera sencilla el metodo, y el **key** `valor` el valor usado. En general:   
 `{'nombre de la columna':{'estrategia':'descripcion de estrategia', 'valor':'valor utilizado'}}`. 
 

De utilizar mas de un metodo puedes anidarlos en una lista  
  `[{...},{...}]`.  

Incluso si la columna utilizada no sufrio imputacion, es necesario que la agregues al JSON.

La idea es que cualquier otra persona pueda cargar el el archivo JSON con tu funcion, entender que hiciste y replicarlo facilmente. No existe solo una respuesta correcta, pero tendras que justificar y explicar tus deciciones.

### Imputacion
En este caso lo que vamos a hacer es iterar sobre el df.columns para ir viendo para cada columna que estrategia en particular hacer, dependiendo del tipo de dato.
1-Para los floats, asumiremos que la distribucion de los datos es relativamente simetrica, por lo tanto para cada uno de los nans lo que vamos a hacer es imputar la media de la columna
2-para los ints, en este caso tomaremos en cuenta que los ints son todos aquellas columnas que representan un ID, asi que no tiene sentido en el caso del int, asignar su media ya que solo son, en este caso, identificadores los ints por lo tanto asignamos un missing ya que uno regularmente no trabaja con id's para prediccioness sino para identificar a una cierta tupla o usuario.
3- En los objects y dates usamos missing para no crear ambiguedades ni mentiras en los datos, y tomamos en cuenta solo los datos de los usuarios que si tienen informacion.

In [271]:
# Tu codigo aqui
#primero quitamos todas las columnas que tiene solo nans
df.dropna(axis=1,how='all',inplace=True)
#ahora quitamos las filas que tienen todos los valores nans
df.dropna(axis=0,how='all',inplace=True)

import json

# Lista de columnas para manejar valores missing
columnas_a_imputar = list(df.columns)
# Crear un diccionario para almacenar la información de imputación
informacion_imputacion = {}

# Iterar sobre cada columna y elegir una estrategia de imputación
for columna in columnas_a_imputar:
    estrategia = None
    valor = None

    # Elegir la estrategia de imputación según las características de la columna
    #usamos mean para sustituir
    if df[columna].dtype == 'float64':
        estrategia = 'media'
        valor = df[columna].mean()
    #explicacion de porque uso missing en int64 esta en el md de arriba
    #pero en los objects, strings e ints metemos missing
    else:
        estrategia = 'identificador'
        valor = 'missing'

    # Realizar la imputación
    df[columna].fillna(valor, inplace=True)

    # Almacenar la información de imputación en el diccionario
    informacion_imputacion[columna] = {'estrategia': estrategia, 'valor': valor}

### Codigo para salvar y cargar JSONs

In [272]:
# Guardar la información de imputación en un archivo JSON
with open('imputacion.json', 'w') as json_file:
    json.dump(informacion_imputacion, json_file)

In [273]:
#Cargamos el json que hemos creado
with open('imputacion.json') as json_file:
    informacion_imputacion = json.load(json_file)
informacion_imputacion

{'member_id': {'estrategia': 'identificador', 'valor': 'missing'},
 'loan_amnt': {'estrategia': 'media', 'valor': 14886.93},
 'funded_amnt': {'estrategia': 'media', 'valor': 14886.93},
 'funded_amnt_inv': {'estrategia': 'media', 'valor': 14883.9105},
 'term': {'estrategia': 'identificador', 'valor': 'missing'},
 'int_rate': {'estrategia': 'media', 'valor': 13.2780734},
 'installment': {'estrategia': 'media', 'valor': 437.3318244000001},
 'grade': {'estrategia': 'identificador', 'valor': 'missing'},
 'sub_grade': {'estrategia': 'identificador', 'valor': 'missing'},
 'emp_title': {'estrategia': 'identificador', 'valor': 'missing'},
 'emp_length': {'estrategia': 'identificador', 'valor': 'missing'},
 'home_ownership': {'estrategia': 'identificador', 'valor': 'missing'},
 'annual_inc': {'estrategia': 'media', 'valor': 74689.2425825},
 'verification_status': {'estrategia': 'identificador', 'valor': 'missing'},
 'issue_d': {'estrategia': 'identificador', 'valor': 'missing'},
 'loan_status': {'estrategia': 'identificador', 'valor': 'missing'},
 'pymnt_plan': {'estrategia': 'identificador', 'valor': 'missing'},
 'desc': {'estrategia': 'identificador', 'valor': 'missing'},
 'purpose': {'estrategia': 'identificador', 'valor': 'missing'},
 'title': {'estrategia': 'identificador', 'valor': 'missing'},
 'zip_code': {'estrategia': 'identificador', 'valor': 'missing'},
 'addr_state': {'estrategia': 'identificador', 'valor': 'missing'},
 'dti': {'estrategia': 'media', 'valor': 18.7697866},
 'delinq_2yrs': {'estrategia': 'media', 'valor': 0.34392},
 'earliest_cr_line': {'estrategia': 'identificador', 'valor': 'missing'},
 'fico_range_low': {'estrategia': 'media', 'valor': 692.5798},
 'fico_range_high': {'estrategia': 'media', 'valor': 696.57987},
 'inq_last_6mths': {'estrategia': 'media', 'valor': 0.62189},
 'mths_since_last_delinq': {'estrategia': 'media',
  'valor': 33.522525683763185},
 'mths_since_last_record': {'estrategia': 'media', 'valor': 69.39421467846043},
 'open_acc': {'estrategia': 'media', 'valor': 11.83275},
 'pub_rec': {'estrategia': 'media', 'valor': 0.21456},
 'revol_bal': {'estrategia': 'media', 'valor': 17588.06238},
 'revol_util': {'estrategia': 'media', 'valor': 55.434984591371176},
 'total_acc': {'estrategia': 'media', 'valor': 26.03486},
 'initial_list_status': {'estrategia': 'identificador', 'valor': 'missing'},
 'out_prncp': {'estrategia': 'media', 'valor': 1215.1084604999999},
 'out_prncp_inv': {'estrategia': 'media', 'valor': 1214.9064667},
 'total_pymnt': {'estrategia': 'media', 'valor': 15210.210257400642},
 'total_pymnt_inv': {'estrategia': 'media', 'valor': 15207.1216847},
 'total_rec_prncp': {'estrategia': 'media', 'valor': 11978.8756247},
 'total_rec_int': {'estrategia': 'media', 'valor': 3040.9570177000005},
 'total_rec_late_fee': {'estrategia': 'media', 'valor': 1.2300369003639051},
 'recoveries': {'estrategia': 'media', 'valor': 189.14756099939245},
 'collection_recovery_fee': {'estrategia': 'media',
  'valor': 31.41689079499522},
 'last_pymnt_d': {'estrategia': 'identificador', 'valor': 'missing'},
 'last_pymnt_amnt': {'estrategia': 'media', 'valor': 4165.111319039872},
 'next_pymnt_d': {'estrategia': 'identificador', 'valor': 'missing'},
 'last_credit_pull_d': {'estrategia': 'identificador', 'valor': 'missing'},
 'last_fico_range_high': {'estrategia': 'media', 'valor': 677.92764},
 'last_fico_range_low': {'estrategia': 'media', 'valor': 664.18765},
 'collections_12_mths_ex_med': {'estrategia': 'media', 'valor': 0.01701},
 'mths_since_last_major_derog': {'estrategia': 'media',
  'valor': 43.45123653412548},
 'policy_code': {'estrategia': 'media', 'valor': 1.0},
 'application_type': {'estrategia': 'identificador', 'valor': 'missing'},
 'acc_now_delinq': {'estrategia': 'media', 'valor': 0.00638},
 'tot_coll_amt': {'estrategia': 'media', 'valor': 235.46884},
 'tot_cur_bal': {'estrategia': 'media', 'valor': 140910.91011},
 'total_rev_hi_lim': {'estrategia': 'media', 'valor': 32526.9722},
 'acc_open_past_24mths': {'estrategia': 'media', 'valor': 4.52473},
 'avg_cur_bal': {'estrategia': 'media', 'valor': 13337.70501},
 'bc_open_to_buy': {'estrategia': 'media', 'valor': 8956.451808021038},
 'bc_util': {'estrategia': 'media', 'valor': 64.5600220643307},
 'chargeoff_within_12_mths': {'estrategia': 'media', 'valor': 0.0104},
 'delinq_amnt': {'estrategia': 'media', 'valor': 11.5565},
 'mo_sin_old_il_acct': {'estrategia': 'media', 'valor': 127.73700163929355},
 'mo_sin_old_rev_tl_op': {'estrategia': 'media', 'valor': 185.82682},
 'mo_sin_rcnt_rev_tl_op': {'estrategia': 'media', 'valor': 13.13111},
 'mo_sin_rcnt_tl': {'estrategia': 'media', 'valor': 7.94572},
 'mort_acc': {'estrategia': 'media', 'valor': 1.78588},
 'mths_since_recent_bc': {'estrategia': 'media', 'valor': 24.435205303635133},
 'mths_since_recent_bc_dlq': {'estrategia': 'media',
  'valor': 39.63386883386883},
 'mths_since_recent_inq': {'estrategia': 'media', 'valor': 6.7667716395733075},
 'mths_since_recent_revol_delinq': {'estrategia': 'media',
  'valor': 35.615431382302546},
 'num_accts_ever_120_pd': {'estrategia': 'media', 'valor': 0.52372},
 'num_actv_bc_tl': {'estrategia': 'media', 'valor': 3.72897},
 'num_actv_rev_tl': {'estrategia': 'media', 'valor': 5.83361},
 'num_bc_sats': {'estrategia': 'media', 'valor': 4.66532},
 'num_bc_tl': {'estrategia': 'media', 'valor': 8.42365},
 'num_il_tl': {'estrategia': 'media', 'valor': 8.66296},
 'num_op_rev_tl': {'estrategia': 'media', 'valor': 8.39263},
 'num_rev_accts': {'estrategia': 'media', 'valor': 15.28991},
 'num_rev_tl_bal_gt_0': {'estrategia': 'media', 'valor': 5.81747},
 'num_sats': {'estrategia': 'media', 'valor': 11.79017},
 'num_tl_120dpd_2m': {'estrategia': 'media', 'valor': 0.0008159601811431602},
 'num_tl_30dpd': {'estrategia': 'media', 'valor': 0.00444},
 'num_tl_90g_dpd_24m': {'estrategia': 'media', 'valor': 0.09143},
 'num_tl_op_past_12m': {'estrategia': 'media', 'valor': 2.0957},
 'pct_tl_nvr_dlq': {'estrategia': 'media', 'valor': 94.300697},
 'percent_bc_gt_75': {'estrategia': 'media', 'valor': 50.694696425500055},
 'pub_rec_bankruptcies': {'estrategia': 'media', 'valor': 0.12654},
 'tax_liens': {'estrategia': 'media', 'valor': 0.05618},
 'tot_hi_cred_lim': {'estrategia': 'media', 'valor': 172385.51452},
 'total_bal_ex_mort': {'estrategia': 'media', 'valor': 50471.32121},
 'total_bc_limit': {'estrategia': 'media', 'valor': 21073.77013},
 'total_il_high_credit_limit': {'estrategia': 'media', 'valor': 41031.31849},
 'hardship_flag': {'estrategia': 'identificador', 'valor': 'missing'},
 'hardship_type': {'estrategia': 'identificador', 'valor': 'missing'},
 'hardship_reason': {'estrategia': 'identificador', 'valor': 'missing'},
 'hardship_status': {'estrategia': 'identificador', 'valor': 'missing'},
 'deferral_term': {'estrategia': 'media', 'valor': 3.0},
 'hardship_amount': {'estrategia': 'media', 'valor': 110.33556756756755},
 'hardship_start_date': {'estrategia': 'identificador', 'valor': 'missing'},
 'hardship_end_date': {'estrategia': 'identificador', 'valor': 'missing'},
 'payment_plan_start_date': {'estrategia': 'identificador',
  'valor': 'missing'},
 'hardship_length': {'estrategia': 'media', 'valor': 3.0},
 'hardship_dpd': {'estrategia': 'media', 'valor': 14.037837837837838},
 'hardship_loan_status': {'estrategia': 'identificador', 'valor': 'missing'},
 'orig_projected_additional_accrued_interest': {'estrategia': 'media',
  'valor': 323.49513157894734},
 'hardship_payoff_balance_amount': {'estrategia': 'media',
  'valor': 8046.61654054054},
 'hardship_last_payment_amount': {'estrategia': 'media',
  'valor': 186.56313513513513},
 'disbursement_method': {'estrategia': 'identificador', 'valor': 'missing'},
 'debt_settlement_flag': {'estrategia': 'identificador', 'valor': 'missing'},
 'debt_settlement_flag_date': {'estrategia': 'identificador',
  'valor': 'missing'},
 'settlement_status': {'estrategia': 'identificador', 'valor': 'missing'},
 'settlement_date': {'estrategia': 'identificador', 'valor': 'missing'},
 'settlement_amount': {'estrategia': 'media', 'valor': 4768.376356589148},
 'settlement_percentage': {'estrategia': 'media', 'valor': 47.720519379844966},
 'settlement_term': {'estrategia': 'media', 'valor': 8.265116279069767}}